dist: trusty
language: minimal

env:
  secure: jpENq2QYFvKFKnfYk/AIkAwHTfEG1EIGFoNNgfGcXrwln0bdf+dR7dP2oUfF5gNw6o1054zRMCjvGozvd7OSYhBKMBI/hu+HsRWPXzVDpwEgSSBgOBLAbstoqNSeBhFNpvYQ63hyt1am28OEvs0L2cKkXE0dxa4DU91emK6nfD4IMIvAv8c4Bz3AwH8ndO2F0nZCbhtCBX0tOWZi6SJz2iT6eeBVtxmyLwriKA5aVLWC7a9Vw1uiJvqkv56/ZDbuDWmEZGiGBdDGZck0qkDOMvdTbK8WSs96LA07IhGcANlIZRYKvDPC4Mub3SV3F2x14lb7WBl3RRdVw4UL6qRnOyZm/+SwMLTMoZrTbZlE7wG2tY19HFpjI5HVL2WiIoJxEgF12Q/+Ol5Z+hv9Y7c6eCZhe4kpQDiJWLYzLZHC++YvjBb9A9MvPpZfNVGjy8+lERE3M5As/qeKOzdpn9dj67D17N/32F62xPVBnnJtXg0gw2kmwQZ2FMG/7/B+HGhAoV+pePDGBdvknmDq31JK2QleOveYhadHf0pc95vwg58CLDY/73wKfHVpd+fvEbXrtWwQUrYrxxbTNgXNGKNSiBB3pg1++R4pv8wJZQMeouFWeSOzXBv+8I0tQkdeO2QC6lQRk2YIcoWrIkEA9O69rjc3Szzjjj02741vApjeIkI=

script:
- rm -rf ./builds/
- ls -1d src/* | xargs -I{} rsync -r {} builds/
- ls -1d builds/* | xargs -I{} zip -rDj {}.zip {}
- find ./builds/ -type f -name "*.zip" -exec sh -c "md5sum {} | cut -d\" \" -f1 > {}.md5.txt" \;
- find ./builds/* -type d | xargs -I{} rm -rf {}

deploy:
  provider: releases
  file_glob: true
  file: "./builds/*"
  body: Lambda functions
  skip-cleanup: true
  on:
    repo: Tweddle-SE-Team/tw-edge-functions
    tags: true
  api_key: "$GITHUB_TOKEN"

