dist: trusty

script:
- rm -rf */edge/builds/
- ls -1d */edge/ | xargs -I{} rsync -Rr {}/./ {}/builds/
- ls -1d */edge/builds/* | xargs -I{} zip -rDj {}/edge-function.zip {}
- cd ../
- zip -r build-${TRAVIS_TAG}.zip tw-edge-functions

deploy:
  provider: releases
  file: build-${TRAVIS_TAG}.zip
  skip-cleanup: true
  on:
    repo: Tweddle-SE-Team/tw-edge-functions
    tags: true
  api_key:
    secure: F0LkNPedrDSdVmrhM9ZEXnmqiHtTobcy4TdQ1NHNBAjmHN7ayADtcQ+hFbYhQ4PeqvEjluU9QBZYrwLF1Iu0d3DoL+B0gqoKHUsXdRdXWMONbfZf2xSvyw2jGvoW6UKYAyWK2htY7ErAf545/0KBd5vABHeMsPHjRtzVN0ZuOI15rSIBuNSjdDRbAM1UiPE+ShpQbnf/YLDgePAyIgbaX0+DwYvHwtHk3zOCVp1DBD4BvL+lc2dMpRKlG8NirRqXMKrCT1ceqWQbOiTSQPmc4UsnqIubuUO/UcaXYL9EqzuGuWr164lugwSGqI4F0Fpx+GRYmYQTCKWBzl8ocNTmkZ20SpaBizi5MgAle5mpebzVzHcydQtwxWS3KL173vgJ9d1XxrVadZwBMMpEhF1GwNhgHVirHx8BrIcMO5BOxIiRPtigHIufwb8Y6GNCP2G7DQl8YiEdwox6yf7/GmGCpG55kLs7/s49GTfmc890cZL1jYpYa8wy4YcF4nv1QXNW0d93jjyQWeJYuXv2IyRlptLvd5VortBB0qAygjtZjwChbc8E2gKUAZM7jFrev7NEaUnfFyxuGz1dGnU0aC5xPm7Do5N+XxmLOYig8fSdOEVGEDjKV+46PRKkxjseX0cHdmka/jgJUvMGETP2mAkkPAhyIFhp6GVnCu8y+RXEuYk=
