dist: trusty
language: minimal

#GITHUB_TOKEN
env:
  secure: AR0iUsZvILGEotQUWkW6oXg+OkI/VylAwkvlYI9X87jwevS4ZWHaos8Xe1cb5CpoLd+0pWnjlp++SbpR/o/HfzHCh5ueId15WHXiEYfe3VDKZqQ9U/XBAh+BmCbDYAOGs02CMsXMoHkRERBxBk5KfPrhuvPx69wKcLvuCCn/o0AkUVymeIKV2vbHxC7e5GMe1FXLPz/drjHDa78hUStXCvVxRUK6rErlyBse5esTE7EYsUb0Vb6LPvMLyyIEqoAy5rE2QP2MP52i9l5XF6gqiEIpOGLZoOjc2IiIp3bDxHGNmeZI+n06B2ArhcqjRVLYcZz8EBcP1dcp4cLTgvopp46DIChvwiThM2Tt8AXaQhG+HEqXtOCbkNZzGpUJT2tHLpv+9GJ2bIII3jh/JZ679RwZ14B+EvFLDxUcFyE5PJz5dLZ/007sSNbZdsvUCVHqlytHF5ApICivbxi/HrraFm636eDC+VtHGDWsUG1Ibe8/sUdcRq1UDQfQ5uHN5F0zPnUbQuziRbPYz+a2r7LuH3H+29iwcuG5osfo5oVX/pZqCPo3ms5yP9SRqQHr1EYYevM/zr5fCjpUoQOt1fNh1v4ZYK6b7WJSQot9tL7xnRBX2rD6Lv0a/+uTeofS8js5ZX1kR2qyOi99kqGKAkdGDbz+6rigDG/pIZGgOK4PZBU=

script:
- rm -rf ./builds/
- ls -1d src/* | xargs -I{} rsync -r {} builds/
- ls -1d builds/* | xargs -I{} zip -rDj {}.zip {}
- find ./builds/ -type f -name "*.zip" -exec sh -c "md5sum {} | cut -d\" \" -f1 > {}.md5.txt" \;
- find ./builds/* -type d | xargs -I{} rm -rf {}

deploy:
  provider: releases
  file_glob: true
  file: "./builds/*"
  body: Lambda functions
  skip-cleanup: true
  on:
    repo: Tweddle-SE-Team/tw-edge-functions
    tags: true
  api_key: $GITHUB_TOKEN
